import type IBlogPane from "../BlogPane/BlogPane.types";
import type IProductsPane from "../ProductsPane/ProductsPane.types";

const seasonCategories = [
  { name: "Zabawki", to: "./agasd" },
  { name: "Wakacyjne", to: "./agasd" },
  { name: "Category 3", to: "./agasd" },
  { name: "Category 4", to: "./agasd" },
  { name: "Category 5", to: "./agasd" },
  { name: "Category 6", to: "./agasd" },
  { name: "Category 7", to: "./agasd" },
  { name: "Category 8", to: "./agasd" },
];

const blogPane: IBlogPane = {
  id: "blog-pane",
  title: "Ostatnio na Blogu",
  extraSliderClass: "",
  posts: [
    {
      title: "Voluptatem accusantium doloremque laudantium",
      image: "assets/images/blog-post/blog_big_01.jpg",
      author: "Jone Doe",
      timestamp: 234623462346,
      description:
        "Sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.",
      to: "/dadgasdasdg",
    },
    {
      title: "Voluptatem accusantium doloremque laudantium",
      image: "assets/images/blog-post/blog_big_02.jpg",
      author: "Jone Doe",
      timestamp: 234623462346,
      description:
        "Sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.",
      to: "/dadgasdasdg",
    },
    {
      title: "Voluptatem accusantium doloremque laudantium",
      image: "assets/images/blog-post/blog_big_03.jpg",
      author: "Jone Doe",
      timestamp: 234623462346,
      description:
        "Sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.",
      to: "/dadgasdasdg",
    },
    {
      title: "Voluptatem accusantium doloremque laudantium",
      image: "assets/images/blog-post/blog_big_01.jpg",
      author: "Jone Doe",
      timestamp: 234623462346,
      description:
        "Sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.",
      to: "/dadgasdasdg",
    },
    {
      title: "Voluptatem accusantium doloremque laudantium",
      image: "assets/images/blog-post/blog_big_02.jpg",
      author: "Jone Doe",
      timestamp: 234623462346,
      description:
        "Sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.",
      to: "/dadgasdasdg",
    },
  ],
};

const newProducts: IProductsPane = {
  id: "new-products-1",
  title: "Nowe produkty",
  sliders: [
    {
      name: "UBRANIA",
      target: "ubrania",
      products: [
        {
          title: "TEST PRODUCT 3434f",
          image: "assets/images/products/p1.jpg",
          hoverImage: "assets/images/products/p1_hover.jpg",
          price: 50,
          priceBefore: 70,
          to: "/sdgdsgds",
          status: "HOT",
        },
        {
          title: "TEST PRODUCT sdssdgsg",
          image: "assets/images/products/p2.jpg",
          hoverImage: "assets/images/products/p2_hover.jpg",
          price: 230,
          priceBefore: 390,
          to: "/sdgddghsgds",
          status: "SALE",
        },
        {
          title: "TEST PRODUCTE sgsdfhsfdhsf",
          image: "assets/images/products/p3.jpg",
          hoverImage: "assets/images/products/p3_hover.jpg",
          price: 2440,
          priceBefore: 3550,
          to: "/sdgdsgxcvnvds",
          status: "NEW",
        },
        {
          title: "TEST PRODUCT sfgsfg",
          image: "assets/images/products/p4.jpg",
          hoverImage: "assets/images/products/p4_hover.jpg",
          price: 20,
          priceBefore: 34635,
          to: "/sdgdsgds",
          status: "NONE",
        },
        {
          title: "TEST PROxdfgxdfg xfCT",
          image: "assets/images/products/p5.jpg",
          hoverImage: "assets/images/products/p5_hover.jpg",
          price: 206,
          priceBefore: 305,
          to: "/sdgdsgcbcnds",
          status: "NONE",
        },
        {
          title: "TEST PRODUCT sfgsfg",
          image: "assets/images/products/p4.jpg",
          hoverImage: "assets/images/products/p4_hover.jpg",
          price: 20,
          priceBefore: 34635,
          to: "/sdgdsgds",
          status: "NONE",
        },
        {
          title: "TEST PROxdfgxdfg xfCT",
          image: "assets/images/products/p5.jpg",
          hoverImage: "assets/images/products/p5_hover.jpg",
          price: 206,
          priceBefore: 305,
          to: "/sdgdsgcbcnds",
          status: "NONE",
        },
        {
          title: "TEST PRODUCT sfgsfg",
          image: "assets/images/products/p4.jpg",
          hoverImage: "assets/images/products/p4_hover.jpg",
          price: 20,
          priceBefore: 34635,
          to: "/sdgdsgds",
          status: "NONE",
        },
        {
          title: "TEST PROxdfgxdfg xfCT",
          image: "assets/images/products/p5.jpg",
          hoverImage: "assets/images/products/p5_hover.jpg",
          price: 206,
          priceBefore: 305,
          to: "/sdgdsgcbcnds",
          status: "NONE",
        },
      ],
    },
    {
      name: "MOTORYZACJA",
      target: "motoryzacja",
      products: [
        {
          title: "TEST PRODUCT 3434f",
          image: "assets/images/products/p4.jpg",
          hoverImage: "assets/images/products/p4_hover.jpg",
          price: 50,
          priceBefore: 70,
          to: "/sdgdsgds",
          status: "HOT",
        },
        {
          title: "TEST PRODUCT sdssdgsg",
          image: "assets/images/products/p3.jpg",
          hoverImage: "assets/images/products/p3_hover.jpg",
          price: 230,
          priceBefore: 390,
          to: "/sdgddghsgds",
          status: "SALE",
        },
        {
          title: "TEST PRODUCTE sgsdfhsfdhsf",
          image: "assets/images/products/p3.jpg",
          hoverImage: "assets/images/products/p3_hover.jpg",
          price: 2440,
          priceBefore: 3550,
          to: "/sdgdsgxcvnvds",
          status: "NEW",
        },
        {
          title: "TEST PRODUCT sfgsfg",
          image: "assets/images/products/p4.jpg",
          hoverImage: "assets/images/products/p4_hover.jpg",
          price: 20,
          priceBefore: 34635,
          to: "/sdgdsgds",
          status: "NONE",
        },
        {
          title: "TEST PROxdfgxdfg xfCT",
          image: "assets/images/products/p5.jpg",
          hoverImage: "assets/images/products/p5_hover.jpg",
          price: 206,
          priceBefore: 305,
          to: "/sdgdsgcbcnds",
          status: "NONE",
        },
        {
          title: "TEST PRODUCT sfgsfg",
          image: "assets/images/products/p4.jpg",
          hoverImage: "assets/images/products/p4_hover.jpg",
          price: 20,
          priceBefore: 34635,
          to: "/sdgdsgds",
          status: "NONE",
        },
        {
          title: "TEST PROxdfgxdfg xfCT",
          image: "assets/images/products/p5.jpg",
          hoverImage: "assets/images/products/p5_hover.jpg",
          price: 206,
          priceBefore: 305,
          to: "/sdgdsgcbcnds",
          status: "NONE",
        },
        {
          title: "TEST PRODUCT sfgsfg",
          image: "assets/images/products/p4.jpg",
          hoverImage: "assets/images/products/p4_hover.jpg",
          price: 20,
          priceBefore: 34635,
          to: "/sdgdsgds",
          status: "NONE",
        },
        {
          title: "TEST PROxdfgxdfg xfCT",
          image: "assets/images/products/p5.jpg",
          hoverImage: "assets/images/products/p5_hover.jpg",
          price: 206,
          priceBefore: 305,
          to: "/sdgdsgcbcnds",
          status: "NONE",
        },
      ],
    },
    {
      name: "ZABAWKI",
      target: "ZABAWKI",
      products: [
        {
          title: "TEST PRODUCT 343sdfsfh4f",
          image: "assets/images/products/p1.jpg",
          hoverImage: "assets/images/products/p1_hover.jpg",
          price: 50,
          priceBefore: 70,
          to: "/sdgdsgds",
          status: "HOT",
        },
        {
          title: "TEST PRODUCT sdssdgsg",
          image: "assets/images/products/p2.jpg",
          hoverImage: "assets/images/products/p2_hover.jpg",
          price: 230,
          priceBefore: 390,
          to: "/sdgddghsgds",
          status: "SALE",
        },
        {
          title: "TEST PRODUCTE sgsdfhsfdhsf",
          image: "assets/images/products/p3.jpg",
          hoverImage: "assets/images/products/p3_hover.jpg",
          price: 2440,
          priceBefore: 3550,
          to: "/sdgdsgxcvnvds",
          status: "NEW",
        },
        {
          title: "TEST PRODUCT sfgsfg",
          image: "assets/images/products/p4.jpg",
          hoverImage: "assets/images/products/p4_hover.jpg",
          price: 20,
          priceBefore: 34635,
          to: "/sdgdsgds",
          status: "NONE",
        },
        {
          title: "TEST PROxdfgxdfg xfCT",
          image: "assets/images/products/p5.jpg",
          hoverImage: "assets/images/products/p5_hover.jpg",
          price: 206,
          priceBefore: 305,
          to: "/sdgdsgcbcnds",
          status: "NONE",
        },
        {
          title: "TEST PROxdfgxdfg xfCT",
          image: "assets/images/products/p5.jpg",
          hoverImage: "assets/images/products/p5_hover.jpg",
          price: 206,
          priceBefore: 305,
          to: "/sdgdsgcbcnds",
          status: "NONE",
        },
        {
          title: "TEST PROxdfgxdfg xfCT",
          image: "assets/images/products/p5.jpg",
          hoverImage: "assets/images/products/p5_hover.jpg",
          price: 206,
          priceBefore: 305,
          to: "/sdgdsgcbcnds",
          status: "NONE",
        },
        {
          title: "TEST PRODUCT sfgsfg",
          image: "assets/images/products/p4.jpg",
          hoverImage: "assets/images/products/p4_hover.jpg",
          price: 20,
          priceBefore: 34635,
          to: "/sdgdsgds",
          status: "NONE",
        },
        {
          title: "TEST PROxdfgxdfg xfCT",
          image: "assets/images/products/p5.jpg",
          hoverImage: "assets/images/products/p5_hover.jpg",
          price: 206,
          priceBefore: 305,
          to: "/sdgdsgcbcnds",
          status: "NONE",
        },
        {
          title: "TEST PRODUCT sfgsfg",
          image: "assets/images/products/p4.jpg",
          hoverImage: "assets/images/products/p4_hover.jpg",
          price: 20,
          priceBefore: 34635,
          to: "/sdgdsgds",
          status: "NONE",
        },
        {
          title: "TEST PROxdfgxdfg xfCT",
          image: "assets/images/products/p5.jpg",
          hoverImage: "assets/images/products/p5_hover.jpg",
          price: 206,
          priceBefore: 305,
          to: "/sdgdsgcbcnds",
          status: "NONE",
        },
      ],
    },
  ],
};

const featuredProducts: IProductsPane = {
  id: "featured-products-1",
  title: "Nowe produkty",
  sliders: [
    {
      name: "UBRANIA",
      target: "ubrania",
      products: [
        {
          title: "TEST PRODUCT 3434f",
          image: "assets/images/products/p1.jpg",
          hoverImage: "assets/images/products/p1_hover.jpg",
          price: 50,
          priceBefore: 70,
          to: "/sdgdsgds",
          status: "HOT",
        },
        {
          title: "TEST PRODUCT sdssdgsg",
          image: "assets/images/products/p2.jpg",
          hoverImage: "assets/images/products/p2_hover.jpg",
          price: 230,
          priceBefore: 390,
          to: "/sdgddghsgds",
          status: "SALE",
        },
        {
          title: "TEST PRODUCTE sgsdfhsfdhsf",
          image: "assets/images/products/p3.jpg",
          hoverImage: "assets/images/products/p3_hover.jpg",
          price: 2440,
          priceBefore: 3550,
          to: "/sdgdsgxcvnvds",
          status: "NEW",
        },
        {
          title: "TEST PRODUCT sfgsfg",
          image: "assets/images/products/p4.jpg",
          hoverImage: "assets/images/products/p4_hover.jpg",
          price: 20,
          priceBefore: 34635,
          to: "/sdgdsgds",
          status: "NONE",
        },
        {
          title: "TEST PROxdfgxdfg xfCT",
          image: "assets/images/products/p5.jpg",
          hoverImage: "assets/images/products/p5_hover.jpg",
          price: 206,
          priceBefore: 305,
          to: "/sdgdsgcbcnds",
          status: "NONE",
        },
        {
          title: "TEST PRODUCT sfgsfg",
          image: "assets/images/products/p4.jpg",
          hoverImage: "assets/images/products/p4_hover.jpg",
          price: 20,
          priceBefore: 34635,
          to: "/sdgdsgds",
          status: "NONE",
        },
        {
          title: "TEST PROxdfgxdfg xfCT",
          image: "assets/images/products/p5.jpg",
          hoverImage: "assets/images/products/p5_hover.jpg",
          price: 206,
          priceBefore: 305,
          to: "/sdgdsgcbcnds",
          status: "NONE",
        },
        {
          title: "TEST PRODUCT sfgsfg",
          image: "assets/images/products/p4.jpg",
          hoverImage: "assets/images/products/p4_hover.jpg",
          price: 20,
          priceBefore: 34635,
          to: "/sdgdsgds",
          status: "NONE",
        },
        {
          title: "TEST PROxdfgxdfg xfCT",
          image: "assets/images/products/p5.jpg",
          hoverImage: "assets/images/products/p5_hover.jpg",
          price: 206,
          priceBefore: 305,
          to: "/sdgdsgcbcnds",
          status: "NONE",
        },
      ],
    },
  ],
};

export { featuredProducts, newProducts, blogPane, seasonCategories };
